port: 8080
collector:
  sensor-tables:
    temperature:
    - temp
    humidity:
    - humidity
    particle:
    - particles03um
    - particles05um
    - particles10um
    - particles25um
    - particles50um
    - particles100um
  warning-levels:
    humidity: 70
  emergency-action:
    humidity: "send-mail"